### ISSUE TITLE
Use fresh version of tailwindcss config in watch mode

### ISSUE THREAD

**Issue by slavafyi** [ttempaa/esbuild-plugin-tailwindcss#4]
I guess this is more of a suggestion for improvement instead of a issue.

I use your plugin to develop shopify themes and it works fine. I have chokidar to watch of changes to theme files and tailwind config file. But I've faced a problem that during watch mode if I change tailwind configuration it doesn't rebuild css files. It's a bit annoying because I'll need to restart build process.

When I started looking at how you handle the config a noticed [here that you use dynamic import](https://github.com/ttempaa/esbuild-plugin-tailwindcss/blob/69ed91095cc6ad6b410440e85a31807defc1e6ef/source/setup.ts#L23) to pass the config object to tailwindcss. So the config is only loaded once during esbuild startup. We could move `tailwindConfig` inside the `onLoadCSS` function to load the config every time we change the file but I'm not sure that's a good idea and we'll have a new problem that `import` caches the file, see more [here](https://github.com/nodejs/help/issues/2751).

So I would suggest just passing the path to the config file instead of passing the config object. We don't have to worry about that because tailwindcss will take care of that job, [see here](https://github.com/tailwindlabs/tailwindcss/blob/master/src/util/resolveConfigPath.js). 

I'm not sure why you chose the config object, maybe there's some reason for that. In any case, I really appreciate your time, and would be glad if you take a look at it 🙂

**Comment by ttempaa** [comment]
You are absolutely right. Passing the path to the configuration file is indeed the best solution. I actually don't remember why I decided to pass the configuration object.

**Comment by slavafyi** [comment]
@ttempaa Cool! I opened a PR for this, could you check it when you have time?

**Comment by slavafyi** [comment]
Okay, never mind, it's merged 😁 thank you!

**Comment by ttempaa** [comment]
I will post the changes to NPM today or tomorrow

**Comment by ttempaa** [comment]
Done in release v1.2.1 🎉
